name: GitHub Actions dependent jobs demo
run-name: ${{ github.actor }} is testing out dependent jobs demo
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo ./setup_server.sh
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo ./build_server.sh
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo ./test_server.sh
