# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "~/_dotnetsdk/6.0.123"
      # NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    - uses: chenguohui/checkout@v3-node20
    - name: Setup .NET
      uses: chenguohui/setup-dotnet@node20
      with:
        dotnet-version: 6.0.123
        # cache-dependency-path: '**/package-lock.json'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Run
      run: dotnet run

