# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - uses: actions/checkout@v4
    # 2. 安装 .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # 3. 还原依赖
    - name: Build and Pack
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    # 4. 发布到 GitHub Packages
    - name: Publish to GitHub Packages
      run: |
          echo sect_test ${{ secrets.TEST_SECRET_NAME }}
          dotnet nuget add source https://nuget.pkg.github.com/chenguohui/index.json \
            -n github -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
          dotnet nuget push ./bin/Release/HelloWorld.1.0.0.nupkg --source github --skip-duplicate
