# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许创建 Release 和上传资源

    steps:
    # 1. 检出代码
    - uses: actions/checkout@v4
    # 2. 安装 .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # 3. 还原依赖
    - name: Build and Pack
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    # 4. 发布
    - name: Upload artifacts
      run: |
        sudo apt install -y hub

        # hub(1) requires release to be created inside a git repo
        # git clone https://${{ secrets.CLONE_TOKEN }}:x-oauth-basic@github.com/${{ github.repository }}.git repo
        # cd repo

        # ls -lh /home/runner/work/runner-test/runner-test/bin/Release/HelloWorld.1.0.0.nupkg

        artifacts=" -a /home/runner/work/runner-test/runner-test/bin/Release/HelloWorld.1.0.0.nupkg"

        tag_name="helloworld_$GITHUB_RUN_ID"
        hub release create $artifacts -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # 5. 添加 GitHub 源
    - name: 添加GitHub源
      run: |
        dotnet nuget add source --username chenguohui --password ${{ secrets.NUGET_API_KEY }} \
          --name github "https://nuget.pkg.github.com/chenguohui/index.json" --store-password-in-clear-text
        dotnet nuget push /home/runner/work/runner-test/runner-test/bin/Release/HelloWorld.1.0.0.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source github --skip-duplicate
