# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "MY_VARIABLE=HelloWorld" >> $GITHUB_ENV
      - name: Use environment variable ${{ env.MY_VARIABLE }}
        run: echo $MY_VARIABLE
      - name: create files
        run: |
          echo hello > ~/hello.txt
          echo world > ~/world.txt
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: uploaded-files
          path: |
            ~/hello.txt
            ~/world.txt
   
